### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by lyccyl1** [ZhengfanCMU/15618_project#1]
hi sir!  I am compiling your project. But I meet the problem that I can't find the dataset u use. Can u push it . 
thx a lot

**Comment by lyccyl1** [comment]
And could u plz tell me where dataset should be placed. How to build ur project. thx

**Comment by ZhengfanCMU** [comment]
Due to the size of the dataset, I'm not going to push it.
Dataset is MNIST from http://yann.lecun.com/exdb/mnist/.
Put the dataset under the following directories. You might have to unzip them.
data/train-images-idx3-ubyte
data/train-labels-idx1-ubyte
